// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/challenges/code.proto (package spotify.login5.v3.challenges, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/challenges/code.proto.
 */
export const file_spotify_login5_v3_challenges_code: GenFile = /*@__PURE__*/
  fileDesc("CidzcG90aWZ5L2xvZ2luNS92My9jaGFsbGVuZ2VzL2NvZGUucHJvdG8SHHNwb3RpZnkubG9naW41LnYzLmNoYWxsZW5nZXMivAEKDUNvZGVDaGFsbGVuZ2USQgoGbWV0aG9kGAEgASgOMjIuc3BvdGlmeS5sb2dpbjUudjMuY2hhbGxlbmdlcy5Db2RlQ2hhbGxlbmdlLk1ldGhvZBITCgtjb2RlX2xlbmd0aBgCIAEoBRISCgpleHBpcmVzX2luGAMgASgFEh4KFmNhbm9uaWNhbF9waG9uZV9udW1iZXIYBCABKAkiHgoGTWV0aG9kEgsKB1VOS05PV04QABIHCgNTTVMQASIcCgxDb2RlU29sdXRpb24SDAoEY29kZRgBIAEoCUI4CiZjb20uc3BvdGlmeS5sb2dpbjUudjMuY2hhbGxlbmdlcy5wcm90b0gCUAGiAglTUFRMb2dpbjViBnByb3RvMw");

/**
 * @generated from message spotify.login5.v3.challenges.CodeChallenge
 */
export type CodeChallenge = Message<"spotify.login5.v3.challenges.CodeChallenge"> & {
  /**
   * @generated from field: spotify.login5.v3.challenges.CodeChallenge.Method method = 1;
   */
  method: CodeChallenge_Method;

  /**
   * @generated from field: int32 code_length = 2;
   */
  codeLength: number;

  /**
   * @generated from field: int32 expires_in = 3;
   */
  expiresIn: number;

  /**
   * @generated from field: string canonical_phone_number = 4;
   */
  canonicalPhoneNumber: string;
};

/**
 * Describes the message spotify.login5.v3.challenges.CodeChallenge.
 * Use `create(CodeChallengeSchema)` to create a new message.
 */
export const CodeChallengeSchema: GenMessage<CodeChallenge> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_challenges_code, 0);

/**
 * @generated from enum spotify.login5.v3.challenges.CodeChallenge.Method
 */
export enum CodeChallenge_Method {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: SMS = 1;
   */
  SMS = 1,
}

/**
 * Describes the enum spotify.login5.v3.challenges.CodeChallenge.Method.
 */
export const CodeChallenge_MethodSchema: GenEnum<CodeChallenge_Method> = /*@__PURE__*/
  enumDesc(file_spotify_login5_v3_challenges_code, 0, 0);

/**
 * @generated from message spotify.login5.v3.challenges.CodeSolution
 */
export type CodeSolution = Message<"spotify.login5.v3.challenges.CodeSolution"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message spotify.login5.v3.challenges.CodeSolution.
 * Use `create(CodeSolutionSchema)` to create a new message.
 */
export const CodeSolutionSchema: GenMessage<CodeSolution> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_challenges_code, 1);

