// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/challenges/hashcash.proto (package spotify.login5.v3.challenges, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/challenges/hashcash.proto.
 */
export const file_spotify_login5_v3_challenges_hashcash: GenFile = /*@__PURE__*/
  fileDesc("CitzcG90aWZ5L2xvZ2luNS92My9jaGFsbGVuZ2VzL2hhc2hjYXNoLnByb3RvEhxzcG90aWZ5LmxvZ2luNS52My5jaGFsbGVuZ2VzIjMKEUhhc2hjYXNoQ2hhbGxlbmdlEg4KBnByZWZpeBgBIAEoDBIOCgZsZW5ndGgYAiABKAUiTwoQSGFzaGNhc2hTb2x1dGlvbhIOCgZzdWZmaXgYASABKAwSKwoIZHVyYXRpb24YAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25COAomY29tLnNwb3RpZnkubG9naW41LnYzLmNoYWxsZW5nZXMucHJvdG9IAlABogIJU1BUTG9naW41YgZwcm90bzM", [file_google_protobuf_duration]);

/**
 * @generated from message spotify.login5.v3.challenges.HashcashChallenge
 */
export type HashcashChallenge = Message<"spotify.login5.v3.challenges.HashcashChallenge"> & {
  /**
   * @generated from field: bytes prefix = 1;
   */
  prefix: Uint8Array;

  /**
   * @generated from field: int32 length = 2;
   */
  length: number;
};

/**
 * Describes the message spotify.login5.v3.challenges.HashcashChallenge.
 * Use `create(HashcashChallengeSchema)` to create a new message.
 */
export const HashcashChallengeSchema: GenMessage<HashcashChallenge> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_challenges_hashcash, 0);

/**
 * @generated from message spotify.login5.v3.challenges.HashcashSolution
 */
export type HashcashSolution = Message<"spotify.login5.v3.challenges.HashcashSolution"> & {
  /**
   * @generated from field: bytes suffix = 1;
   */
  suffix: Uint8Array;

  /**
   * @generated from field: google.protobuf.Duration duration = 2;
   */
  duration?: Duration;
};

/**
 * Describes the message spotify.login5.v3.challenges.HashcashSolution.
 * Use `create(HashcashSolutionSchema)` to create a new message.
 */
export const HashcashSolutionSchema: GenMessage<HashcashSolution> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_challenges_hashcash, 1);

