// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/client_info.proto (package spotify.login5.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/client_info.proto.
 */
export const file_spotify_login5_v3_client_info: GenFile = /*@__PURE__*/
  fileDesc("CiNzcG90aWZ5L2xvZ2luNS92My9jbGllbnRfaW5mby5wcm90bxIRc3BvdGlmeS5sb2dpbjUudjMiMgoKQ2xpZW50SW5mbxIRCgljbGllbnRfaWQYASABKAkSEQoJZGV2aWNlX2lkGAIgASgJQi0KG2NvbS5zcG90aWZ5LmxvZ2luNS52My5wcm90b0gCUAGiAglTUFRMb2dpbjViBnByb3RvMw");

/**
 * @generated from message spotify.login5.v3.ClientInfo
 */
export type ClientInfo = Message<"spotify.login5.v3.ClientInfo"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string device_id = 2;
   */
  deviceId: string;
};

/**
 * Describes the message spotify.login5.v3.ClientInfo.
 * Use `create(ClientInfoSchema)` to create a new message.
 */
export const ClientInfoSchema: GenMessage<ClientInfo> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_client_info, 0);

