// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/user_info.proto (package spotify.login5.v3, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/user_info.proto.
 */
export const file_spotify_login5_v3_user_info: GenFile = /*@__PURE__*/
  fileDesc("CiFzcG90aWZ5L2xvZ2luNS92My91c2VyX2luZm8ucHJvdG8SEXNwb3RpZnkubG9naW41LnYzIpcCCghVc2VySW5mbxIMCgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhYKDmVtYWlsX3ZlcmlmaWVkGAMgASgIEhEKCWJpcnRoZGF0ZRgEIAEoCRIyCgZnZW5kZXIYBSABKA4yIi5zcG90aWZ5LmxvZ2luNS52My5Vc2VySW5mby5HZW5kZXISFAoMcGhvbmVfbnVtYmVyGAYgASgJEh0KFXBob25lX251bWJlcl92ZXJpZmllZBgHIAEoCBIgChhlbWFpbF9hbHJlYWR5X3JlZ2lzdGVyZWQYCCABKAgiOAoGR2VuZGVyEgsKB1VOS05PV04QABIICgRNQUxFEAESCgoGRkVNQUxFEAISCwoHTkVVVFJBTBADQi0KG2NvbS5zcG90aWZ5LmxvZ2luNS52My5wcm90b0gCUAGiAglTUFRMb2dpbjViBnByb3RvMw");

/**
 * @generated from message spotify.login5.v3.UserInfo
 */
export type UserInfo = Message<"spotify.login5.v3.UserInfo"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: bool email_verified = 3;
   */
  emailVerified: boolean;

  /**
   * @generated from field: string birthdate = 4;
   */
  birthdate: string;

  /**
   * @generated from field: spotify.login5.v3.UserInfo.Gender gender = 5;
   */
  gender: UserInfo_Gender;

  /**
   * @generated from field: string phone_number = 6;
   */
  phoneNumber: string;

  /**
   * @generated from field: bool phone_number_verified = 7;
   */
  phoneNumberVerified: boolean;

  /**
   * @generated from field: bool email_already_registered = 8;
   */
  emailAlreadyRegistered: boolean;
};

/**
 * Describes the message spotify.login5.v3.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema: GenMessage<UserInfo> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_user_info, 0);

/**
 * @generated from enum spotify.login5.v3.UserInfo.Gender
 */
export enum UserInfo_Gender {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: MALE = 1;
   */
  MALE = 1,

  /**
   * @generated from enum value: FEMALE = 2;
   */
  FEMALE = 2,

  /**
   * @generated from enum value: NEUTRAL = 3;
   */
  NEUTRAL = 3,
}

/**
 * Describes the enum spotify.login5.v3.UserInfo.Gender.
 */
export const UserInfo_GenderSchema: GenEnum<UserInfo_Gender> = /*@__PURE__*/
  enumDesc(file_spotify_login5_v3_user_info, 0, 0);

