// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/credentials/credentials.proto (package spotify.login5.v3.credentials, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/credentials/credentials.proto.
 */
export const file_spotify_login5_v3_credentials_credentials: GenFile = /*@__PURE__*/
  fileDesc("Ci9zcG90aWZ5L2xvZ2luNS92My9jcmVkZW50aWFscy9jcmVkZW50aWFscy5wcm90bxIdc3BvdGlmeS5sb2dpbjUudjMuY3JlZGVudGlhbHMiMgoQU3RvcmVkQ3JlZGVudGlhbBIQCgh1c2VybmFtZRgBIAEoCRIMCgRkYXRhGAIgASgMIjkKCFBhc3N3b3JkEgoKAmlkGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEg8KB3BhZGRpbmcYAyABKAwiOwoTRmFjZWJvb2tBY2Nlc3NUb2tlbhIOCgZmYl91aWQYASABKAkSFAoMYWNjZXNzX3Rva2VuGAIgASgJIh0KDE9uZVRpbWVUb2tlbhINCgV0b2tlbhgBIAEoCSJ8ChVQYXJlbnRDaGlsZENyZWRlbnRpYWwSEAoIY2hpbGRfaWQYASABKAkSUQoYcGFyZW50X3N0b3JlZF9jcmVkZW50aWFsGAIgASgLMi8uc3BvdGlmeS5sb2dpbjUudjMuY3JlZGVudGlhbHMuU3RvcmVkQ3JlZGVudGlhbCJTChVBcHBsZVNpZ25JbkNyZWRlbnRpYWwSEQoJYXV0aF9jb2RlGAEgASgJEhQKDHJlZGlyZWN0X3VyaRgCIAEoCRIRCglidW5kbGVfaWQYAyABKAkicAoXU2Ftc3VuZ1NpZ25JbkNyZWRlbnRpYWwSEQoJYXV0aF9jb2RlGAEgASgJEhQKDHJlZGlyZWN0X3VyaRgCIAEoCRIQCghpZF90b2tlbhgDIAEoCRIaChJ0b2tlbl9lbmRwb2ludF91cmwYBCABKAkiQQoWR29vZ2xlU2lnbkluQ3JlZGVudGlhbBIRCglhdXRoX2NvZGUYASABKAkSFAoMcmVkaXJlY3RfdXJpGAIgASgJQjkKJ2NvbS5zcG90aWZ5LmxvZ2luNS52My5jcmVkZW50aWFscy5wcm90b0gCUAGiAglTUFRMb2dpbjViBnByb3RvMw");

/**
 * @generated from message spotify.login5.v3.credentials.StoredCredential
 */
export type StoredCredential = Message<"spotify.login5.v3.credentials.StoredCredential"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message spotify.login5.v3.credentials.StoredCredential.
 * Use `create(StoredCredentialSchema)` to create a new message.
 */
export const StoredCredentialSchema: GenMessage<StoredCredential> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 0);

/**
 * @generated from message spotify.login5.v3.credentials.Password
 */
export type Password = Message<"spotify.login5.v3.credentials.Password"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: bytes padding = 3;
   */
  padding: Uint8Array;
};

/**
 * Describes the message spotify.login5.v3.credentials.Password.
 * Use `create(PasswordSchema)` to create a new message.
 */
export const PasswordSchema: GenMessage<Password> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 1);

/**
 * @generated from message spotify.login5.v3.credentials.FacebookAccessToken
 */
export type FacebookAccessToken = Message<"spotify.login5.v3.credentials.FacebookAccessToken"> & {
  /**
   * @generated from field: string fb_uid = 1;
   */
  fbUid: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;
};

/**
 * Describes the message spotify.login5.v3.credentials.FacebookAccessToken.
 * Use `create(FacebookAccessTokenSchema)` to create a new message.
 */
export const FacebookAccessTokenSchema: GenMessage<FacebookAccessToken> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 2);

/**
 * @generated from message spotify.login5.v3.credentials.OneTimeToken
 */
export type OneTimeToken = Message<"spotify.login5.v3.credentials.OneTimeToken"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message spotify.login5.v3.credentials.OneTimeToken.
 * Use `create(OneTimeTokenSchema)` to create a new message.
 */
export const OneTimeTokenSchema: GenMessage<OneTimeToken> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 3);

/**
 * @generated from message spotify.login5.v3.credentials.ParentChildCredential
 */
export type ParentChildCredential = Message<"spotify.login5.v3.credentials.ParentChildCredential"> & {
  /**
   * @generated from field: string child_id = 1;
   */
  childId: string;

  /**
   * @generated from field: spotify.login5.v3.credentials.StoredCredential parent_stored_credential = 2;
   */
  parentStoredCredential?: StoredCredential;
};

/**
 * Describes the message spotify.login5.v3.credentials.ParentChildCredential.
 * Use `create(ParentChildCredentialSchema)` to create a new message.
 */
export const ParentChildCredentialSchema: GenMessage<ParentChildCredential> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 4);

/**
 * @generated from message spotify.login5.v3.credentials.AppleSignInCredential
 */
export type AppleSignInCredential = Message<"spotify.login5.v3.credentials.AppleSignInCredential"> & {
  /**
   * @generated from field: string auth_code = 1;
   */
  authCode: string;

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri: string;

  /**
   * @generated from field: string bundle_id = 3;
   */
  bundleId: string;
};

/**
 * Describes the message spotify.login5.v3.credentials.AppleSignInCredential.
 * Use `create(AppleSignInCredentialSchema)` to create a new message.
 */
export const AppleSignInCredentialSchema: GenMessage<AppleSignInCredential> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 5);

/**
 * @generated from message spotify.login5.v3.credentials.SamsungSignInCredential
 */
export type SamsungSignInCredential = Message<"spotify.login5.v3.credentials.SamsungSignInCredential"> & {
  /**
   * @generated from field: string auth_code = 1;
   */
  authCode: string;

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri: string;

  /**
   * @generated from field: string id_token = 3;
   */
  idToken: string;

  /**
   * @generated from field: string token_endpoint_url = 4;
   */
  tokenEndpointUrl: string;
};

/**
 * Describes the message spotify.login5.v3.credentials.SamsungSignInCredential.
 * Use `create(SamsungSignInCredentialSchema)` to create a new message.
 */
export const SamsungSignInCredentialSchema: GenMessage<SamsungSignInCredential> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 6);

/**
 * @generated from message spotify.login5.v3.credentials.GoogleSignInCredential
 */
export type GoogleSignInCredential = Message<"spotify.login5.v3.credentials.GoogleSignInCredential"> & {
  /**
   * @generated from field: string auth_code = 1;
   */
  authCode: string;

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri: string;
};

/**
 * Describes the message spotify.login5.v3.credentials.GoogleSignInCredential.
 * Use `create(GoogleSignInCredentialSchema)` to create a new message.
 */
export const GoogleSignInCredentialSchema: GenMessage<GoogleSignInCredential> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_credentials_credentials, 7);

