// Extracted from: Spotify 1.1.33.569 (Windows)

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spotify/login5/v3/identifiers/identifiers.proto (package spotify.login5.v3.identifiers, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spotify/login5/v3/identifiers/identifiers.proto.
 */
export const file_spotify_login5_v3_identifiers_identifiers: GenFile = /*@__PURE__*/
  fileDesc("Ci9zcG90aWZ5L2xvZ2luNS92My9pZGVudGlmaWVycy9pZGVudGlmaWVycy5wcm90bxIdc3BvdGlmeS5sb2dpbjUudjMuaWRlbnRpZmllcnMiVQoLUGhvbmVOdW1iZXISDgoGbnVtYmVyGAEgASgJEhgKEGlzb19jb3VudHJ5X2NvZGUYAiABKAkSHAoUY291bnRyeV9jYWxsaW5nX2NvZGUYAyABKAlCOQonY29tLnNwb3RpZnkubG9naW41LnYzLmlkZW50aWZpZXJzLnByb3RvSAJQAaICCVNQVExvZ2luNWIGcHJvdG8z");

/**
 * @generated from message spotify.login5.v3.identifiers.PhoneNumber
 */
export type PhoneNumber = Message<"spotify.login5.v3.identifiers.PhoneNumber"> & {
  /**
   * @generated from field: string number = 1;
   */
  number: string;

  /**
   * @generated from field: string iso_country_code = 2;
   */
  isoCountryCode: string;

  /**
   * @generated from field: string country_calling_code = 3;
   */
  countryCallingCode: string;
};

/**
 * Describes the message spotify.login5.v3.identifiers.PhoneNumber.
 * Use `create(PhoneNumberSchema)` to create a new message.
 */
export const PhoneNumberSchema: GenMessage<PhoneNumber> = /*@__PURE__*/
  messageDesc(file_spotify_login5_v3_identifiers_identifiers, 0);

